export  const userModalTemplate = {
  firstName: null,
  lastName: null,
  birthDate: null,
  directionId: null,
  education: null,
  startDate: null,
  sex: null,
  email: null,
  university: null,
  mathScore: null,
  adress: null,
  mobilePhone: null,
  skype: null,
};